### ISSUE TITLE
[QUESTION] Higher level libraries to serialize the kernels?

### ISSUE THREAD

**Issue by echarles** [jupyter-server/synchronizer#70]
This has been discussed on https://stackoverflow.com/questions/34342155/how-to-pickle-or-store-jupyter-ipython-notebook-session-for-later

https://github.com/uqfoundation/dill sounds like a thing that could also be useful.

@blink1073

**Comment by blink1073** [comment]
This library is using sqlite to store the information, building on what jupyter server is already doing.  I think any other type of serialization format is out of scope.

cc @Zsailer

**Comment by Zsailer** [comment]
> This library is using sqlite to store the information, building on what jupyter server is already doing. 

Yeah, that's right. This simply extends the sqlite database already found in Jupyter Server to include an extra table about kernels. I purposely kept this extension as simple as possible. 

That said, I think server (i.e. sessions and kernels) rehydration is a place we can certainly standardize somewhere in the Jupyter Server org. In enterprise_gateway, [the kernel sessions can be persisted by serializing to JSON and writing to file](https://github.com/jupyter-server/enterprise_gateway/blob/08d606002e110b3b44a01abb5eb5bb3401dcbead/enterprise_gateway/services/sessions/kernelsessionmanager.py#L329-L395). There is a lot of redundant logic between EG and synchronizer that we might be able to unify. 

I don't think it's wise to serialize the literal instance of the Python KernelManager object—pickling objects is always a messy task. Rather, like EG and synchronizer, we should identify the necessary data in the KernelManager that we can serialize/deserialize. 

To move forward, I think the next step is to define some sort of specification for the kernel manager describing the required fields. I think `kernel_id`, `kernel_name`, and the connection_info dict are the minimal requirements. I started to build a KernelRecord [dataclass that provides a good starting point](https://github.com/jupyter-server/synchronizer/blob/8d04960f3f89edc0f2c9cc9cde109c860fcb79ca/jupyter_server_synchronizer/kernel_records.py#L17-L32).

cc @kevin-bates

**Comment by kevin-bates** [comment]
Thanks for the ping.

First, I think we need to be clear that neither this package or EG serializes _kernel state_ - which is what the SO link in the description is driving at.  To that point, I think the opening description of this repo is a bit misleading:

_A Jupyter Server Session Manager that rehydrates and persists kernels and sessions beyond the lifetime of a server._

and should probably be amended to something more like:

_A Jupyter Server Session Manager that persists and rehydrates kernel sessions beyond the lifetime of a server._

The persistence we're talking about here and in EG (with process proxies) is simply the ability of a server application to rehydrate sessions to _existing_ kernels.  As a result, the use-case we're driving at is relative to remote kernels since, in all likelihood, a server _crash_ will take with it any local kernels as well, and, once the kernel has terminated, there's no way to reconnect to it.  (That said, persistence/rehydration shouldn't preclude local kernels from its solution.  You can always _try_ to reconnect.) So it's really one of DR (Disaster Recovery) but could be utilized in some capacity for HA (High Availability).

I strongly believe kernel _session_ persistence is the **purview of the kernel provisioner** (EG's process proxies) but the _driver_ for persistence/rehydration would likely reside in the application `KernelManager`. (Probably on the newly introduced `ServerKernelManager` since I don't think this has the necessary application for pure, _single-kernel_, `jupyter_client` applications.)

------
(What follows is a description of how this all works in EG today and that there are already hooks for this in provisioners)

When a kernel starts in EG, the `RemoteMappingKernelManager` [creates a `KernelSession` which captures high-level details, then asks the process proxy instance to "persist itself into this dictionary".](https://github.com/jupyter-server/enterprise_gateway/blob/08d606002e110b3b44a01abb5eb5bb3401dcbead/enterprise_gateway/services/sessions/kernelsessionmanager.py#L81-L110)  The persistence methods then are invoked on _each class_ of the hierarchy where **each class knows what fields its needs to persist in order to re-establish lifecycle management** with that _same_ kernel instance later.  Once that method returns (and all classes in the hierarchy have "had their chance") the result is persisted into shared storage. 

For example, the [`KuberenetesProcessProxy` needs to know the namespace the kernel pod is running in, along with a flag determining if that namespace should be deleted upon termination.](https://github.com/jupyter-server/enterprise_gateway/blob/08d606002e110b3b44a01abb5eb5bb3401dcbead/enterprise_gateway/services/processproxies/k8s.py#L353).  Its superclass `ContainerProcessProxy` needs to know the IP of the node.  Its superclass `RemoteProcessProxy`, etc. etc.

Knowing this was needed for provisioners, the [`KernelProvisionerBase`](https://github.com/jupyter/jupyter_client/blob/5a12a3842563c682dd462eb73000adff1fcedd0f/jupyter_client/provisioning/provisioner_base.py#L17) ABC provides base implementations for [`get_provisioner_info()`](https://github.com/jupyter/jupyter_client/blob/5a12a3842563c682dd462eb73000adff1fcedd0f/jupyter_client/provisioning/provisioner_base.py#L173-L186) and [`load_provisioner_info()`](https://github.com/jupyter/jupyter_client/blob/5a12a3842563c682dd462eb73000adff1fcedd0f/jupyter_client/provisioning/provisioner_base.py#L188-L200) and are already serializing `kernel_id` and `connection_info`.

So, I would view the synchronizer to be analogous to EG's `KernelSessionManager`.  Note that in process proxies, the connection info is not maintained in the process proxy, like it is with provisioners.  Also note, that the way this persistence sequence works, it's okay to have redundancy in the persisted information.  Sure, we'd like to minimize that, but we also only care that each subclass of the provisioner hierarchy gets what it needs to succeed.  In essence, the persisted information is opaque.

**Comment by echarles** [comment]
Thx a lot all for these very useful feedbacks.

`...kernels and sessions...` -> `...kernel sessions...` - Yes, the `kernel and sessions` has maybe confused me. Now I clearly see that this extension persist the needed information to reconnect on server restart to existing kernels (hosted e.g. in EG). It does not deal with serializing kernel content (the variables...).

I am closing this as answered.

**Comment by Zsailer** [comment]
> First, I think we need to be clear that neither this package or EG serializes kernel state - which is what the SO link in the description is driving at

Ah, yes. Thank you, Kevin. I didn't realize that the goal of the original post was to serialize the whole kernel state.

**Comment by Zsailer** [comment]
> A Jupyter Server Session Manager that persists and rehydrates kernel sessions beyond the lifetime of a server.

:+1: Changing...
